version: '3.0'

services:
  productPage:
    build: ./productPage/.
    image: 35/productpage
    container_name: 35-productpage
    ports:
      - '9080:9080'
    environment:
      - GROUP_NUMBER=35
      - ENABLE_RATINGS=true
  
  details:
    build: ./details/.
    image: 35/details
    container_name: 35-details
    environment:
      - SERVICE_VERSION=v1
      - ENABLE_EXTERNAL_BOOK_SERVICE=true
    depends_on: 
      - productPage
  
  reviews:
    build: ./practica_creativa2/bookinfo/src/reviews/reviews-wlpcfg/.
    image: 35/reviews
    container_name: 35-reviews
    environment:
      - ENABLE_RATINGS=true
    depends_on: 
      - productPage
  
  ratings:
    build: ./ratings/.
    image: 35/ratings
    container_name: 35-ratings
    environment:
      - SERVICE_VERSION=v1
    depends_on: 
      - reviews
  
  
