##################################################################################################
# Productpage service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
    service: productpage
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: productpage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-v1
  labels:
    app: productpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      containers:
      - name: productpage
        image: <GROUP_NUMBER>/productpage
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        securityContext:
          runAsUser: 1000
      env:
      - name: DETAILS
      value: "details:9080"
      - name: REVIEWS
      value: "reviews:9080"
---
#service que permita acceder por medio de una IP externa a la aplicación por medio del microservicio productpage
apiVersion: v1
kind: Service
metadata:
  - name: productpage-external
spec:
  type: LoadBalancer
  selector:
    app: productpage
  ports:
    - name: http
    port: 9080
    targetport: 9080
